run:
  timeout: 5m

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

linters-settings:
  forbidigo:
    forbid:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
      - fmt.Fprintf
      - fmt.Fprint
      - fmt.Fprintln
  gofmt:
    simplify: true
  govet:
    enable-all: true
    disable:
      - fieldalignment

linters:
  disable-all: true
  enable:
    - gofmt
    - gosimple
    # - govet # Re-enable when all shadow declarations are fixed
    - ineffassign
    - predeclared
    - exportloopref
    - staticcheck
    - unconvert
    - unused
